# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - packr2

builds:
- env:
  - CGO_ENABLED=0
  goos: [darwin, freebsd, linux, windows]
  goarch: [amd64]

archives:
  - replacements:
      darwin: macOS
      amd64: x86_64

    format_overrides:
    - goos: windows
      format: zip
    
    files:
    - LICENSE*
    - README*
    - doc/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
